stages:
  - build

before_script:
  - aws configure set aws_access_key_id ****************
  - aws configure set aws_secret_access_key *********************
  - aws configure set region ap-south-1

build:
  stage: build    
  script:
    - wget https://raw.githubusercontent.com/anchore/grype/main/install.sh
    - ls 
    - bash install.sh
    - docker build -t *********.dkr.ecr.ap-south-1.amazonaws.com/node-api-1:latest .
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin *********.dkr.ecr.ap-south-1.amazonaws.com
    - docker push *********.dkr.ecr.ap-south-1.amazonaws.com/node-api-1:latest
    - ./bin/grype *********..dkr.ecr.ap-south-1.amazonaws.com/node-api-1:latest
    - ./bin/grype  -o json *********.dkr.ecr.ap-south-1.amazonaws.com/node-api-1:latest > scanresult.json
    - docker rmi node-api-1:latest
  artifacts:
    paths:
      - scanresult.json
