stages:
  - build

before_script:
    - docker login --username dharmiksa --password *******

build:
  stage: build    
  script:
    - wget https://raw.githubusercontent.com/anchore/grype/main/install.sh
    - ls 
    - bash install.sh
    - docker build -t dharmiksa/node-api:latest .
    - docker push dharmiksa/node-api:latest
    - ./bin/grype dharmiksa/node-api:latest
    - ./bin/grype -o json dharmiksa/node-api:latest > scanresult.json
    - docker rmi dharmiksa/node-api:latest
  artifacts:
    paths:
      - scanresult.json
